channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7 # nail the python version, so conda does not try upgrading / downgrading
  - ctapipe=0.8
  - zeromq
  - ipython
  - numba
  - numpy>=1.15.4
  - numpydoc
  - pytest
  - pyyaml
  - zlib
  - pip
  - pip:
      - pytest_runner
      - https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.2.tar.gz
